Remove prodclass
machtfit/django-oscar pull request #7
Opened 2017-02-20 17:39 UTC by Azd325

2017-07-04 17:21 UTC, mbertheau requested changes

2017-07-04 17:21 UTC, mbertheau commented on src/oscar/apps/catalogue/abstract_models.py
> -        self.attr = ProductAttributesContainer(product=self)
Das sind ProductAttributes, oder? Nicht ProductClass. Wir wollen zwar auch die Attributes entfernen, aber nicht in diesem Schritt.

2017-07-04 17:21 UTC, mbertheau commented on src/oscar/apps/dashboard/catalogue/app.py
> -                name='catalogue-class-delete'),
Wenn du nach `catalogue-class` suchst findest du noch etwas

2017-07-04 17:21 UTC, mbertheau commented on src/oscar/apps/dashboard/catalogue/views.py
> -        ctx['productclass_form'] = self.productclass_form_class()
Dieser View hier kann auch komplett weg. Er ist dazu da, vor dem Anlegen eines Produktes die Produktklasse auszuwählen.

2017-07-04 17:21 UTC, mbertheau commented on src/oscar/apps/dashboard/catalogue/views.py
> -    template_name = 'dashboard/catalogue/product_class_form.html'
Die Templates hier können auch alle weg.

2017-07-04 17:21 UTC, mbertheau commented on src/oscar/apps/offer/models.py
> +            return self.__class_ids
Methode kann ganz weg, oder?

2017-07-04 17:21 UTC, mbertheau commented on src/oscar/apps/catalogue/abstract_models.py
> -        'catalogue.Option', blank=True, verbose_name=_("Options"))
`requires_shipping`, `track_stock` und `options` sowie `attributes` wird noch an einigen Stellen (oft mit `get_product_class()` geholt. Da sollte stattdessen `requires_shipping = False`, `track_stock = False` und `options` leer hartkodiert werden. `requires_shipping`, `track_stock` sowie die Attribute und Optionen können dann im nächsten Schritt (nächsten PR, gleiches Ticket) komplett entfernt werden.

2017-07-04 17:21 UTC, mbertheau commented on src/oscar/apps/partner/importers.py
> -            name=product_class_name)
In dieser Datei ist auch noch viel Produktklasse drin. Vielleicht kannst du noch vor den Produktklassen dieses Importer-Zeug komplett rausschmeißen. Das sollte ohne Probleme gehen.

2017-07-06 09:38 UTC, Azd325 commented on src/oscar/apps/dashboard/catalogue/views.py
> -    template_name = 'dashboard/catalogue/product_class_form.html'
Sind weg.

2017-07-06 09:38 UTC, Azd325 commented on src/oscar/apps/catalogue/abstract_models.py
> -        'catalogue.Option', blank=True, verbose_name=_("Options"))
Durch eine FakeClass Habe ich das erstmal gelöst.

2017-07-06 09:38 UTC, Azd325 commented on src/oscar/apps/dashboard/catalogue/app.py
> -                name='catalogue-class-delete'),
gelöscht.

2017-07-11 12:13 UTC, merged